# -*- coding: utf-8 -*-
"""Speech_to_text_using_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ydIBfr3B9dA1QYUs1E7-5zlBr8qmotLX
"""

import speech_recognition as sr
import pyttsx3

def get():
  r = sr.Recognizer
  with sr.Microphone() as source:
    print('say something to convert the speech into text ........!')
    audio = r.listen(source)
    print('done!...')

  try: 
    text = r.recognize_google(audio)
    print('you said'+text)
  except Exception as e:
    print e

get()